/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EmployeeRouteImport } from './routes/employee'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppTimesheetsRouteImport } from './routes/_app.timesheets'
import { Route as AppTimeAdjustmentsRouteImport } from './routes/_app.time-adjustments'
import { Route as AppTeamsRouteImport } from './routes/_app.teams'
import { Route as AppScreenshotsRouteImport } from './routes/_app.screenshots'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppProjectsRouteImport } from './routes/_app.projects'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppPeopleRouteImport } from './routes/_app.people'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppLiveActivityRouteImport } from './routes/_app.live-activity'
import { Route as AppEmployeesRouteImport } from './routes/_app.employees'
import { Route as AppDevicesRouteImport } from './routes/_app.devices'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAuditLogRouteImport } from './routes/_app.audit-log'
import { Route as AppTeamsTeamIdRouteImport } from './routes/_app.teams.$teamId'
import { Route as AppSettingsTrackingRouteImport } from './routes/_app.settings.tracking'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app.projects.$projectId'
import { Route as AppEmployeesEmployeeIdRouteImport } from './routes/_app.employees.$employeeId'
import { Route as AppDevicesDeviceIdRouteImport } from './routes/_app.devices.$deviceId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeRoute = EmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTimesheetsRoute = AppTimesheetsRouteImport.update({
  id: '/timesheets',
  path: '/timesheets',
  getParentRoute: () => AppRoute,
} as any)
const AppTimeAdjustmentsRoute = AppTimeAdjustmentsRouteImport.update({
  id: '/time-adjustments',
  path: '/time-adjustments',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamsRoute = AppTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AppRoute,
} as any)
const AppScreenshotsRoute = AppScreenshotsRouteImport.update({
  id: '/screenshots',
  path: '/screenshots',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPeopleRoute = AppPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppLiveActivityRoute = AppLiveActivityRouteImport.update({
  id: '/live-activity',
  path: '/live-activity',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesRoute = AppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppDevicesRoute = AppDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditLogRoute = AppAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamsTeamIdRoute = AppTeamsTeamIdRouteImport.update({
  id: '/$teamId',
  path: '/$teamId',
  getParentRoute: () => AppTeamsRoute,
} as any)
const AppSettingsTrackingRoute = AppSettingsTrackingRouteImport.update({
  id: '/settings/tracking',
  path: '/settings/tracking',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppEmployeesEmployeeIdRoute = AppEmployeesEmployeeIdRouteImport.update({
  id: '/$employeeId',
  path: '/$employeeId',
  getParentRoute: () => AppEmployeesRoute,
} as any)
const AppDevicesDeviceIdRoute = AppDevicesDeviceIdRouteImport.update({
  id: '/$deviceId',
  path: '/$deviceId',
  getParentRoute: () => AppDevicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/download': typeof DownloadRoute
  '/employee': typeof EmployeeRoute
  '/login': typeof LoginRoute
  '/audit-log': typeof AppAuditLogRoute
  '/dashboard': typeof AppDashboardRoute
  '/devices': typeof AppDevicesRouteWithChildren
  '/employees': typeof AppEmployeesRouteWithChildren
  '/live-activity': typeof AppLiveActivityRoute
  '/notifications': typeof AppNotificationsRoute
  '/people': typeof AppPeopleRoute
  '/profile': typeof AppProfileRoute
  '/projects': typeof AppProjectsRouteWithChildren
  '/reports': typeof AppReportsRoute
  '/screenshots': typeof AppScreenshotsRoute
  '/teams': typeof AppTeamsRouteWithChildren
  '/time-adjustments': typeof AppTimeAdjustmentsRoute
  '/timesheets': typeof AppTimesheetsRoute
  '/users': typeof AppUsersRoute
  '/devices/$deviceId': typeof AppDevicesDeviceIdRoute
  '/employees/$employeeId': typeof AppEmployeesEmployeeIdRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/settings/tracking': typeof AppSettingsTrackingRoute
  '/teams/$teamId': typeof AppTeamsTeamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/download': typeof DownloadRoute
  '/employee': typeof EmployeeRoute
  '/login': typeof LoginRoute
  '/audit-log': typeof AppAuditLogRoute
  '/dashboard': typeof AppDashboardRoute
  '/devices': typeof AppDevicesRouteWithChildren
  '/employees': typeof AppEmployeesRouteWithChildren
  '/live-activity': typeof AppLiveActivityRoute
  '/notifications': typeof AppNotificationsRoute
  '/people': typeof AppPeopleRoute
  '/profile': typeof AppProfileRoute
  '/projects': typeof AppProjectsRouteWithChildren
  '/reports': typeof AppReportsRoute
  '/screenshots': typeof AppScreenshotsRoute
  '/teams': typeof AppTeamsRouteWithChildren
  '/time-adjustments': typeof AppTimeAdjustmentsRoute
  '/timesheets': typeof AppTimesheetsRoute
  '/users': typeof AppUsersRoute
  '/devices/$deviceId': typeof AppDevicesDeviceIdRoute
  '/employees/$employeeId': typeof AppEmployeesEmployeeIdRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/settings/tracking': typeof AppSettingsTrackingRoute
  '/teams/$teamId': typeof AppTeamsTeamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/accept-invitation': typeof AcceptInvitationRoute
  '/download': typeof DownloadRoute
  '/employee': typeof EmployeeRoute
  '/login': typeof LoginRoute
  '/_app/audit-log': typeof AppAuditLogRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/devices': typeof AppDevicesRouteWithChildren
  '/_app/employees': typeof AppEmployeesRouteWithChildren
  '/_app/live-activity': typeof AppLiveActivityRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/people': typeof AppPeopleRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/projects': typeof AppProjectsRouteWithChildren
  '/_app/reports': typeof AppReportsRoute
  '/_app/screenshots': typeof AppScreenshotsRoute
  '/_app/teams': typeof AppTeamsRouteWithChildren
  '/_app/time-adjustments': typeof AppTimeAdjustmentsRoute
  '/_app/timesheets': typeof AppTimesheetsRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/devices/$deviceId': typeof AppDevicesDeviceIdRoute
  '/_app/employees/$employeeId': typeof AppEmployeesEmployeeIdRoute
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/_app/settings/tracking': typeof AppSettingsTrackingRoute
  '/_app/teams/$teamId': typeof AppTeamsTeamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invitation'
    | '/download'
    | '/employee'
    | '/login'
    | '/audit-log'
    | '/dashboard'
    | '/devices'
    | '/employees'
    | '/live-activity'
    | '/notifications'
    | '/people'
    | '/profile'
    | '/projects'
    | '/reports'
    | '/screenshots'
    | '/teams'
    | '/time-adjustments'
    | '/timesheets'
    | '/users'
    | '/devices/$deviceId'
    | '/employees/$employeeId'
    | '/projects/$projectId'
    | '/settings/tracking'
    | '/teams/$teamId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invitation'
    | '/download'
    | '/employee'
    | '/login'
    | '/audit-log'
    | '/dashboard'
    | '/devices'
    | '/employees'
    | '/live-activity'
    | '/notifications'
    | '/people'
    | '/profile'
    | '/projects'
    | '/reports'
    | '/screenshots'
    | '/teams'
    | '/time-adjustments'
    | '/timesheets'
    | '/users'
    | '/devices/$deviceId'
    | '/employees/$employeeId'
    | '/projects/$projectId'
    | '/settings/tracking'
    | '/teams/$teamId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/accept-invitation'
    | '/download'
    | '/employee'
    | '/login'
    | '/_app/audit-log'
    | '/_app/dashboard'
    | '/_app/devices'
    | '/_app/employees'
    | '/_app/live-activity'
    | '/_app/notifications'
    | '/_app/people'
    | '/_app/profile'
    | '/_app/projects'
    | '/_app/reports'
    | '/_app/screenshots'
    | '/_app/teams'
    | '/_app/time-adjustments'
    | '/_app/timesheets'
    | '/_app/users'
    | '/_app/devices/$deviceId'
    | '/_app/employees/$employeeId'
    | '/_app/projects/$projectId'
    | '/_app/settings/tracking'
    | '/_app/teams/$teamId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AcceptInvitationRoute: typeof AcceptInvitationRoute
  DownloadRoute: typeof DownloadRoute
  EmployeeRoute: typeof EmployeeRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee': {
      id: '/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof EmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation': {
      id: '/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/timesheets': {
      id: '/_app/timesheets'
      path: '/timesheets'
      fullPath: '/timesheets'
      preLoaderRoute: typeof AppTimesheetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/time-adjustments': {
      id: '/_app/time-adjustments'
      path: '/time-adjustments'
      fullPath: '/time-adjustments'
      preLoaderRoute: typeof AppTimeAdjustmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teams': {
      id: '/_app/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AppTeamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/screenshots': {
      id: '/_app/screenshots'
      path: '/screenshots'
      fullPath: '/screenshots'
      preLoaderRoute: typeof AppScreenshotsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/people': {
      id: '/_app/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof AppPeopleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/live-activity': {
      id: '/_app/live-activity'
      path: '/live-activity'
      fullPath: '/live-activity'
      preLoaderRoute: typeof AppLiveActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees': {
      id: '/_app/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AppEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/devices': {
      id: '/_app/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof AppDevicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit-log': {
      id: '/_app/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AppAuditLogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teams/$teamId': {
      id: '/_app/teams/$teamId'
      path: '/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof AppTeamsTeamIdRouteImport
      parentRoute: typeof AppTeamsRoute
    }
    '/_app/settings/tracking': {
      id: '/_app/settings/tracking'
      path: '/settings/tracking'
      fullPath: '/settings/tracking'
      preLoaderRoute: typeof AppSettingsTrackingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/employees/$employeeId': {
      id: '/_app/employees/$employeeId'
      path: '/$employeeId'
      fullPath: '/employees/$employeeId'
      preLoaderRoute: typeof AppEmployeesEmployeeIdRouteImport
      parentRoute: typeof AppEmployeesRoute
    }
    '/_app/devices/$deviceId': {
      id: '/_app/devices/$deviceId'
      path: '/$deviceId'
      fullPath: '/devices/$deviceId'
      preLoaderRoute: typeof AppDevicesDeviceIdRouteImport
      parentRoute: typeof AppDevicesRoute
    }
  }
}

interface AppDevicesRouteChildren {
  AppDevicesDeviceIdRoute: typeof AppDevicesDeviceIdRoute
}

const AppDevicesRouteChildren: AppDevicesRouteChildren = {
  AppDevicesDeviceIdRoute: AppDevicesDeviceIdRoute,
}

const AppDevicesRouteWithChildren = AppDevicesRoute._addFileChildren(
  AppDevicesRouteChildren,
)

interface AppEmployeesRouteChildren {
  AppEmployeesEmployeeIdRoute: typeof AppEmployeesEmployeeIdRoute
}

const AppEmployeesRouteChildren: AppEmployeesRouteChildren = {
  AppEmployeesEmployeeIdRoute: AppEmployeesEmployeeIdRoute,
}

const AppEmployeesRouteWithChildren = AppEmployeesRoute._addFileChildren(
  AppEmployeesRouteChildren,
)

interface AppProjectsRouteChildren {
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRoute
}

const AppProjectsRouteChildren: AppProjectsRouteChildren = {
  AppProjectsProjectIdRoute: AppProjectsProjectIdRoute,
}

const AppProjectsRouteWithChildren = AppProjectsRoute._addFileChildren(
  AppProjectsRouteChildren,
)

interface AppTeamsRouteChildren {
  AppTeamsTeamIdRoute: typeof AppTeamsTeamIdRoute
}

const AppTeamsRouteChildren: AppTeamsRouteChildren = {
  AppTeamsTeamIdRoute: AppTeamsTeamIdRoute,
}

const AppTeamsRouteWithChildren = AppTeamsRoute._addFileChildren(
  AppTeamsRouteChildren,
)

interface AppRouteChildren {
  AppAuditLogRoute: typeof AppAuditLogRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDevicesRoute: typeof AppDevicesRouteWithChildren
  AppEmployeesRoute: typeof AppEmployeesRouteWithChildren
  AppLiveActivityRoute: typeof AppLiveActivityRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPeopleRoute: typeof AppPeopleRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProjectsRoute: typeof AppProjectsRouteWithChildren
  AppReportsRoute: typeof AppReportsRoute
  AppScreenshotsRoute: typeof AppScreenshotsRoute
  AppTeamsRoute: typeof AppTeamsRouteWithChildren
  AppTimeAdjustmentsRoute: typeof AppTimeAdjustmentsRoute
  AppTimesheetsRoute: typeof AppTimesheetsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppSettingsTrackingRoute: typeof AppSettingsTrackingRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuditLogRoute: AppAuditLogRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDevicesRoute: AppDevicesRouteWithChildren,
  AppEmployeesRoute: AppEmployeesRouteWithChildren,
  AppLiveActivityRoute: AppLiveActivityRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPeopleRoute: AppPeopleRoute,
  AppProfileRoute: AppProfileRoute,
  AppProjectsRoute: AppProjectsRouteWithChildren,
  AppReportsRoute: AppReportsRoute,
  AppScreenshotsRoute: AppScreenshotsRoute,
  AppTeamsRoute: AppTeamsRouteWithChildren,
  AppTimeAdjustmentsRoute: AppTimeAdjustmentsRoute,
  AppTimesheetsRoute: AppTimesheetsRoute,
  AppUsersRoute: AppUsersRoute,
  AppSettingsTrackingRoute: AppSettingsTrackingRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AcceptInvitationRoute: AcceptInvitationRoute,
  DownloadRoute: DownloadRoute,
  EmployeeRoute: EmployeeRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
